services:
  - type: web
    name: forenstix
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind :$PORT --workers 2 --worker-class sync
    autoDeploy: true
